//! LLM provider trait and LLM call types.
//!
//! This module defines the [`LlmProvider`] port trait and the supporting
//! data types for LLM API calls:
//!
//! - [`ChatMessage`] / [`ChatRole`] — the message sequence passed to the API.
//! - [`ModelConfig`] — per-model configuration (context window, costs, etc.).
//! - [`OutputSchema`] — JSON Schema describing the expected completion structure.
//! - [`StructuredResponse`] — validated completion with token accounting.
//! - [`LlmError`] — all failure modes for LLM provider calls.
//!
//! It also contains progressive tool discovery and skill validation types:
//!
//! - [`ToolIndexEntry`] / [`CompactToolIndex`] — compact index for LLM tool discovery.
//! - [`build_compact_index`] / [`search_tools`] — index construction and search.
//! - [`SkillLifecycle`] / [`SkillManifest`] / [`SkillInvocation`] — skill metadata.
//! - [`ValidatedSkillInvocation`] — opaque validated skill invocation token.
//! - [`SkillError`] — skill validation error variants.
//! - [`validate_skill_invocation`] — skill lifecycle, profile, and schema validation.
//!
//! ## LLM Call Flow
//!
//! The `nodes` crate's `LlmGateway` orchestrates constitutional prompt wrapping
//! and rate-limit management before delegating to this trait. The trait
//! itself is the raw provider interface — it does not enforce constitutional
//! rules.
//!
//! ```text
//! nodes::LlmGateway::call(ConstitutionallyWrappedPrompt, context, schema, model)
//!     └── pipeline::LlmProvider::complete(system, messages, schema, model)
//!             └── llm::AnthropicProvider  (or other impl)
//! ```
//!
//! ## Multi-Provider Support
//!
//! Adding a provider is additive: create a new `impl LlmProvider` in the `llm`
//! crate. No changes to `pipeline` are required.
//!
//! ## Architectural Layer
//!
//! Trait defined in `pipeline` (port layer); implemented in the `llm`
//! infrastructure crate (Anthropic, OpenAI, etc.).
//!
//! ## Specification
//!
//! See `docs/spec/interfaces/domain-traits.md` §LLM Provider Trait for the
//! full contract.
//! See `docs/spec/interfaces/advanced-features.md` for tool discovery and
//! skill validation contracts.

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{
    identifiers::{SkillName, ToolName},
    types::TokenCount,
};

// ─── LLM call types ─────────────────────────────────────────────────────────

/// Role of a message in a chat-style LLM conversation.
///
/// See `docs/spec/interfaces/domain-traits.md` §ChatRole.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChatRole {
    /// Instructions and context provided by CogWorks (the system operator).
    System,
    /// Content submitted as if from the end user (prompt and context).
    User,
    /// Content generated by the LLM in a prior turn (used for few-shot examples
    /// or multi-turn flows).
    Assistant,
}

// ---------------------------------------------------------------------------

/// A single message in a chat-style conversation sent to the LLM provider.
///
/// `ChatMessage` is intentionally immutable: once constructed the role and
/// content cannot be changed. Mutation after construction would allow callers
/// to bypass the injection guard that validates content before the message is
/// assembled into a prompt.
///
/// Use the convenience constructors [`ChatMessage::system`],
/// [`ChatMessage::user`], and [`ChatMessage::assistant`] to build messages.
///
/// See `docs/spec/interfaces/domain-traits.md` §ChatMessage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// The role of the message sender.
    role: ChatRole,
    /// The text content of the message.
    ///
    /// Must not be empty. Constitutional system prompts are included in
    /// the `System` role message; injecting instructions into `User` role
    /// content is detected by the injection guard.
    content: String,
}

impl ChatMessage {
    /// Creates a system-role message.
    ///
    /// Returns `None` if `content` is empty.
    #[must_use]
    pub fn system(content: impl Into<String>) -> Option<Self> {
        let content = content.into();
        if content.is_empty() {
            return None;
        }
        Some(Self {
            role: ChatRole::System,
            content,
        })
    }

    /// Creates a user-role message.
    ///
    /// Returns `None` if `content` is empty.
    #[must_use]
    pub fn user(content: impl Into<String>) -> Option<Self> {
        let content = content.into();
        if content.is_empty() {
            return None;
        }
        Some(Self {
            role: ChatRole::User,
            content,
        })
    }

    /// Creates an assistant-role message (for few-shot examples).
    ///
    /// Returns `None` if `content` is empty.
    #[must_use]
    pub fn assistant(content: impl Into<String>) -> Option<Self> {
        let content = content.into();
        if content.is_empty() {
            return None;
        }
        Some(Self {
            role: ChatRole::Assistant,
            content,
        })
    }

    /// Returns the role of this message.
    pub fn role(&self) -> &ChatRole {
        &self.role
    }

    /// Returns the text content of this message.
    pub fn content(&self) -> &str {
        &self.content
    }
}

// ---------------------------------------------------------------------------

/// A JSON Schema describing the structure of the expected LLM completion.
///
/// The LLM is asked to produce output conforming to this schema, and
/// `StructuredResponse::content` is validated against it before being
/// returned to the caller. Schema validation failures produce
/// [`LlmError::SchemaValidationFailed`].
///
/// See `docs/spec/interfaces/domain-traits.md` §OutputSchema.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputSchema(serde_json::Value);

impl OutputSchema {
    /// Creates an [`OutputSchema`] from a raw JSON Schema value.
    ///
    /// Returns `None` if the value is not a JSON object (all valid JSON
    /// Schemas are objects at the root level).
    #[must_use]
    pub fn new(schema: serde_json::Value) -> Option<Self> {
        if schema.is_object() {
            Some(Self(schema))
        } else {
            None
        }
    }

    /// Returns the raw JSON Schema value.
    pub fn as_value(&self) -> &serde_json::Value {
        &self.0
    }
}

// ---------------------------------------------------------------------------

/// Per-model configuration used to select and account for LLM API calls.
///
/// The `LlmGateway` (in `nodes`) selects a `ModelConfig` based on node
/// configuration. The `StructuredResponse` echoes back the token counts
/// measured against this config.
///
/// See `docs/spec/interfaces/domain-traits.md` §ModelConfig.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelConfig {
    /// Provider-specific model identifier
    /// (e.g. `"claude-3-5-sonnet-20241022"`, `"gpt-4o"`).
    pub model_id: String,
    /// Maximum number of tokens the model's context window can hold
    /// (prompt + completion combined for some providers).
    pub context_window_size: u64,
    /// Maximum completion tokens the provider will return in one call.
    pub max_output_tokens: u64,
    /// Cost in USD per input token (prompt tokens).
    ///
    /// Used for pre-call budget estimation.
    pub input_cost_per_token: f64,
    /// Cost in USD per output token (completion tokens).
    ///
    /// Used for post-call cost accounting.
    pub output_cost_per_token: f64,
}

// ---------------------------------------------------------------------------

/// The validated completion returned by [`LlmProvider::complete`].
///
/// The `content` field has been checked against the [`OutputSchema`] before
/// the response is returned to the caller. If schema validation failed,
/// [`LlmError::SchemaValidationFailed`] is returned instead — this struct
/// is only constructed on success.
///
/// See `docs/spec/interfaces/domain-traits.md` §StructuredResponse.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StructuredResponse {
    /// The completion content, validated against the requested `OutputSchema`.
    content: serde_json::Value,
    /// Number of tokens in the prompt (input tokens billed by the provider).
    input_tokens: TokenCount,
    /// Number of tokens in the completion (output tokens billed by the provider).
    output_tokens: TokenCount,
    /// Wall-clock latency of the API call in milliseconds.
    latency_ms: u64,
}

impl StructuredResponse {
    /// Creates a new validated response.
    ///
    /// [`LlmProvider`] implementations should return
    /// [`LlmError::SchemaValidationFailed`] instead of constructing a response
    /// when validation fails.
    #[must_use]
    pub fn new(
        content: serde_json::Value,
        input_tokens: TokenCount,
        output_tokens: TokenCount,
        latency_ms: u64,
    ) -> Self {
        Self {
            content,
            input_tokens,
            output_tokens,
            latency_ms,
        }
    }

    /// Returns the validated completion content.
    pub fn content(&self) -> &serde_json::Value {
        &self.content
    }

    /// Returns the number of prompt (input) tokens billed by the provider.
    pub fn input_tokens(&self) -> TokenCount {
        self.input_tokens
    }

    /// Returns the number of completion (output) tokens billed by the provider.
    pub fn output_tokens(&self) -> TokenCount {
        self.output_tokens
    }

    /// Returns the wall-clock latency of the API call in milliseconds.
    pub fn latency_ms(&self) -> u64 {
        self.latency_ms
    }
}

// ─── LLM error type ─────────────────────────────────────────────────────────

/// Errors returned by [`LlmProvider::complete`].
///
/// See `docs/spec/interfaces/domain-traits.md` §LlmError.
#[derive(Debug, Error, Serialize, Deserialize)]
pub enum LlmError {
    /// The provider is enforcing a rate limit.
    ///
    /// The `retry_after` duration is derived from `Retry-After` or
    /// `x-ratelimit-reset` response headers when available.
    #[error("LLM provider rate-limited; retry after {retry_after:?}")]
    RateLimited {
        /// Minimum duration to wait before retrying, if known.
        retry_after: Option<std::time::Duration>,
    },

    /// The provider returned a non-2xx HTTP status code.
    #[error("LLM API error (HTTP {status_code}): {message}")]
    ApiError {
        /// HTTP status code from the provider response.
        status_code: u16,
        /// Error message from the provider response body.
        message: String,
    },

    /// The completion was returned but did not conform to the requested
    /// `OutputSchema`.
    ///
    /// The raw completion is included for audit trail and debug purposes.
    /// Callers must not use the `content` field for domain logic — they
    /// should treat this as a failure and apply their retry budget.
    #[error("LLM completion failed schema validation: {violations:?}")]
    SchemaValidationFailed {
        /// Raw completion content that failed validation.
        content: serde_json::Value,
        /// Human-readable descriptions of each schema violation.
        violations: Vec<String>,
    },

    /// A transport-level error occurred before the provider returned a response.
    #[error("LLM provider network error: {message}")]
    NetworkError {
        /// Description of the network failure.
        message: String,
    },

    /// The assembled prompt exceeds the model's context window.
    ///
    /// Callers should reduce the context package (lower summary levels or
    /// fewer items) before retrying.
    #[error(
        "Prompt context window exceeded: requested {requested} tokens, model limit is {limit}"
    )]
    ContextWindowExceeded {
        /// Number of tokens in the assembled prompt.
        requested: TokenCount,
        /// Maximum tokens the model accepts.
        limit: TokenCount,
    },
}

impl LlmError {
    /// Whether this error is likely transient and safe to retry.
    pub fn retry_policy(&self) -> crate::errors::RetryPolicy {
        use crate::errors::RetryPolicy;
        match self {
            Self::RateLimited { retry_after } => RetryPolicy::Retryable {
                after: *retry_after,
            },
            Self::ApiError { status_code, .. } if *status_code >= 500 => {
                RetryPolicy::Retryable { after: None }
            }
            Self::NetworkError { .. } => RetryPolicy::Retryable { after: None },
            // HTTP 408 (Request Timeout) falls through to ApiError and is
            // treated as NonRetryable here. The LlmGateway in `nodes` applies
            // its own retry budget; revisit if 408s prove common in practice.
            Self::ApiError { .. }
            | Self::SchemaValidationFailed { .. }
            | Self::ContextWindowExceeded { .. } => RetryPolicy::NonRetryable,
        }
    }
}

// ─── LLM provider trait ─────────────────────────────────────────────────────

/// Port trait for LLM API providers.
///
/// This trait abstracts over the concrete HTTP API of each LLM provider.
/// The `LlmGateway` in the `nodes` crate wraps this trait with constitutional
/// prompt assembly, rate-limit management, and schema validation retry logic.
///
/// ## Implementors
///
/// - `llm::AnthropicProvider` — Anthropic Messages API (Claude family)
/// - Additional providers are added as new `impl` blocks in the `llm` crate
///   without any changes to `pipeline`.
///
/// ## Constitutional Rules
///
/// The `system_prompt` parameter MUST contain the constitutional rules text.
/// The `LlmGateway` ensures this; direct callers of `LlmProvider::complete`
/// are responsible for passing a constitutionally-safe system prompt.
///
/// ## Architectural Layer
///
/// Trait defined in `pipeline`; implemented in the `llm` infrastructure crate.
///
/// See `docs/spec/interfaces/domain-traits.md` §LlmProvider.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// Sends a chat-style completion request and returns the structured
    /// response.
    ///
    /// # Arguments
    /// - `system_prompt` — the system-role instruction text. This MUST include
    ///   the constitutional rules text (see `docs/spec/security.md`).
    /// - `messages` — the ordered message sequence (user/assistant turns).
    /// - `schema` — JSON Schema the completion must conform to.
    /// - `model` — model selection and cost configuration.
    ///
    /// # Returns
    /// [`StructuredResponse`] with validated `content`, token counts, latency.
    ///
    /// # Errors
    /// - [`LlmError::RateLimited`] — provider rate limit hit; retry after delay.
    /// - [`LlmError::ApiError`] — provider returned a non-2xx response.
    /// - [`LlmError::SchemaValidationFailed`] — completion did not match schema.
    /// - [`LlmError::NetworkError`] — transport failure before response received.
    /// - [`LlmError::ContextWindowExceeded`] — prompt too large for the model.
    ///
    /// # Security
    ///
    /// Never log `messages` content — it may contain proprietary code,
    /// issue descriptions, or other sensitive data. Log only token counts,
    /// model ID, and latency.
    async fn complete(
        &self,
        system_prompt: &str,
        messages: &[ChatMessage],
        schema: &OutputSchema,
        model: &ModelConfig,
    ) -> Result<StructuredResponse, LlmError>;
}

// ─── Progressive tool discovery ──────────────────────────────────────────────

/// A single entry in the compact tool index.
///
/// Used by LLM nodes during progressive tool discovery: the node first receives
/// a [`CompactToolIndex`] and searches for a fitting tool before requesting the
/// full tool definition.
///
/// See `docs/spec/interfaces/advanced-features.md` §ToolIndexEntry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolIndexEntry {
    /// The tool's canonical name.
    pub tool_name: ToolName,

    /// One-line human-readable description of the tool.
    ///
    /// Currently populated as an empty string when built via
    /// [`build_compact_index`]; description enrichment is expected to occur
    /// in the `nodes` crate when the index is assembled for LLM consumption.
    pub description: String,

    /// `true` if this entry represents a composite skill rather than a raw
    /// tool call.
    ///
    /// Skills are ranked before raw tools in [`CompactToolIndex::entries`].
    pub is_skill: bool,
}

// ---------------------------------------------------------------------------

/// An ordered, skill-first list of all available tools and skills.
///
/// Used as the first response to an LLM agent querying which tools exist.
/// The agent searches the compact index to find a tool of interest, then
/// requests its full definition before invoking it.
///
/// ## Ordering
///
/// Skills appear before raw tools. Within each group, entries are sorted
/// alphabetically by `tool_name`.
///
/// See `docs/spec/interfaces/advanced-features.md` §CompactToolIndex.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactToolIndex {
    /// All available tools and skills, skills ranked first then alphabetical.
    pub entries: Vec<ToolIndexEntry>,
}

// ---------------------------------------------------------------------------

/// Constructs a compact tool index from a list of available tool names and
/// their profile metadata.
///
/// # Arguments
///
/// * `tool_list` — canonical names of tools that may be invoked.
/// * `profiles` — tool profiles used to determine which tools are skills.
///
/// # Returns
///
/// A [`CompactToolIndex`] with skills sorted before raw tools; within each
/// group, alphabetical by `tool_name`. [`ToolIndexEntry::description`] is
/// populated as an empty string.
///
/// See `docs/spec/interfaces/advanced-features.md` §build_compact_index.
pub fn build_compact_index(
    _tool_list: &[ToolName],
    _profiles: &[crate::knowledge::ToolProfile],
) -> CompactToolIndex {
    todo!("See docs/spec/interfaces/advanced-features.md §Progressive Tool Discovery")
}

// ---------------------------------------------------------------------------

/// Returns all entries in a [`CompactToolIndex`] whose name or description
/// contains `query` as a case-insensitive substring.
///
/// Matching entries are returned in the same order they appear in
/// `index.entries` (skills before raw tools, alphabetical within each group).
///
/// # Arguments
///
/// * `index` — the compact tool index to search.
/// * `query` — case-insensitive substring to look for in `tool_name` and
///   `description`.
///
/// See `docs/spec/interfaces/advanced-features.md` §search_tools.
pub fn search_tools(_index: &CompactToolIndex, _query: &str) -> Vec<ToolIndexEntry> {
    todo!("See docs/spec/interfaces/advanced-features.md §Progressive Tool Discovery")
}

// ─── Skill validation ────────────────────────────────────────────────────────

/// Lifecycle state of a skill; governs whether the skill may be invoked.
///
/// See `docs/spec/interfaces/advanced-features.md` §SkillLifecycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SkillLifecycle {
    /// Under review, not yet approved for use. Not invocable.
    Proposed,
    /// Review complete but not yet activated. Not invocable.
    Reviewed,
    /// Fully approved. Invocable.
    Active,
    /// Deprecated in favour of `alternative`. Not invocable.
    Deprecated {
        /// The replacement skill that callers should use instead.
        alternative: SkillName,
    },
    /// Permanently removed. Not invocable.
    Retired,
}

impl SkillLifecycle {
    /// Returns `true` if the skill may be invoked (only [`Active`](Self::Active)
    /// lifecycles are invocable).
    #[must_use]
    pub fn is_invocable(&self) -> bool {
        matches!(self, Self::Active)
    }
}

// ---------------------------------------------------------------------------

/// Full specification of a skill, loaded from the skill registry.
///
/// A skill is a pre-composed, validated sequence of raw tool calls with
/// declared scope constraints. LLM nodes prefer skills over raw tools because
/// they reduce the number of turns needed and enforce approvals at the skill
/// level rather than per-tool-call.
///
/// See `docs/spec/interfaces/advanced-features.md` §SkillManifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillManifest {
    /// Canonical skill identifier.
    pub name: SkillName,

    /// Current lifecycle state; determines invocability.
    pub lifecycle: SkillLifecycle,

    /// JSON Schema that skill parameter values must conform to.
    ///
    /// Validated by [`validate_skill_invocation`] before the skill is allowed
    /// to proceed.
    pub parameter_schema: OutputSchema,

    /// Ordered list of raw tool calls this skill expands to.
    ///
    /// The `nodes` crate executes these calls in sequence when the skill is
    /// invoked.
    pub tool_call_sequence: Vec<ToolName>,

    /// Scope restrictions applied when this skill is invoked.
    ///
    /// Merged with the node's active [`crate::ScopeParameters`] at invocation
    /// time; the stricter of the two values applies.
    pub scope_constraints: crate::knowledge::ScopeParameters,
}

// ---------------------------------------------------------------------------

/// A request to invoke a skill, before validation.
///
/// Produced by the `nodes` crate when an LLM agent selects a skill. Must be
/// passed to [`validate_skill_invocation`] before the skill can be executed.
///
/// See `docs/spec/interfaces/advanced-features.md` §SkillInvocation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillInvocation {
    /// The skill to invoke.
    pub skill_name: SkillName,

    /// Caller-supplied parameter values.
    ///
    /// Must conform to [`SkillManifest::parameter_schema`]; validated by
    /// [`validate_skill_invocation`].
    pub parameters: serde_json::Value,
}

// ---------------------------------------------------------------------------

/// Opaque wrapper produced only when skill validation passes.
///
/// The `nodes` crate cannot construct `ValidatedSkillInvocation` directly —
/// it can only be obtained by calling [`validate_skill_invocation`]. This
/// enforces the invariant that a skill can only be executed after it has been
/// validated against its manifest and the active tool profile.
///
/// See `docs/spec/interfaces/advanced-features.md` §ValidatedSkillInvocation.
#[derive(Debug, Clone)]
pub struct ValidatedSkillInvocation {
    /// The validated invocation payload.
    ///
    /// Private — consumers use the public accessor.
    invocation: SkillInvocation,
    /// Resolved tool call sequence from the skill manifest.
    ///
    /// Captured at validation time to prevent TOCTOU issues if the manifest
    /// were to change between validation and execution.
    pub(crate) tool_call_sequence: Vec<ToolName>,
}

impl ValidatedSkillInvocation {
    /// Returns a reference to the validated skill invocation.
    pub fn invocation(&self) -> &SkillInvocation {
        &self.invocation
    }

    /// Returns the ordered tool call sequence resolved at validation time.
    pub fn tool_call_sequence(&self) -> &[ToolName] {
        &self.tool_call_sequence
    }
}

// ---------------------------------------------------------------------------

/// Errors from [`validate_skill_invocation`].
///
/// See `docs/spec/interfaces/advanced-features.md` §SkillError.
#[derive(Debug, thiserror::Error, Serialize, Deserialize)]
pub enum SkillError {
    /// The skill's lifecycle state is not [`SkillLifecycle::Active`].
    #[error("Skill '{skill_name}' lifecycle is not Active")]
    LifecycleInactive {
        /// The skill that was requested.
        skill_name: SkillName,
        /// The actual lifecycle state (serialised as its variant name).
        lifecycle_state: String,
    },

    /// The supplied parameters do not conform to the skill's parameter schema.
    #[error("Skill parameter schema validation failed: {description}")]
    SchemaValidationFailed {
        /// Human-readable description of the validation failure.
        description: String,
    },

    /// The active [`crate::ToolProfile`] does not permit this skill.
    #[error("Skill '{skill_name}' is not permitted by the active tool profile")]
    ProfileProhibited {
        /// The skill that was requested.
        skill_name: SkillName,
    },

    /// No manifest exists for the requested skill name.
    #[error("Unknown skill '{skill_name}'")]
    UnknownSkill {
        /// The name of the skill that was not found.
        skill_name: SkillName,
    },
}

// ---------------------------------------------------------------------------

/// Validates that a skill invocation is permitted by its lifecycle, parameter
/// schema, and active tool profile.
///
/// # Validation Order
///
/// 1. `Err(SkillError::LifecycleInactive)` if `manifest.lifecycle` is not `Active`.
/// 2. `Err(SkillError::ProfileProhibited)` if `manifest.name` is not in
///    `profile.allowed_skills`.
/// 3. `Err(SkillError::SchemaValidationFailed)` if `invocation.parameters`
///    does not conform to `manifest.parameter_schema`.
/// 4. `Ok(ValidatedSkillInvocation { … })` with the resolved tool call sequence.
///
/// # Arguments
///
/// * `invocation` — caller-supplied invocation request.
/// * `manifest` — the skill's full specification (loaded from skill registry).
/// * `profile` — the active tool profile for the current node execution.
///
/// # Returns
///
/// A [`ValidatedSkillInvocation`] on success. The `nodes` crate passes this
/// value to its skill executor to drive the tool call sequence.
///
/// # Errors
///
/// See [`SkillError`] variants.
///
/// See `docs/spec/interfaces/advanced-features.md` §validate_skill_invocation.
pub fn validate_skill_invocation(
    _invocation: &SkillInvocation,
    _manifest: &SkillManifest,
    _profile: &crate::knowledge::ToolProfile,
) -> Result<ValidatedSkillInvocation, SkillError> {
    todo!("See docs/spec/interfaces/advanced-features.md §Skill Validation")
}
